- Cargo.lock
- Cargo.toml
- src/config/schema.rs
- src/config/toml.rs
- src/model/release.rs
- src/sync/archive.rs
- src/sync/download.rs
- src/sync/install.rs
> [#16] Add fancy progress bar

- Cargo.lock
- Cargo.toml
- src/model/tool.rs
- src/sync.rs
- src/sync/archive.rs
- src/sync/download.rs
- src/sync/install.rs
- src/sync/progress.rs
> [#19] Prettier progress formatting

- src/config/schema.rs
- src/config/toml.rs
- src/lib.rs
- src/model/asset_name.rs
> [#4] Add tests for TOML config parsing

- src/sync/install.rs
> [#14] Make tools executable after unpacking

- src/sync/archive.rs
> [#3] Support '.exe' extension in Windows executables

- src/sync/download.rs
> [#17] Support usage of environment variables auth

- src/model/tool.rs
- src/sync/configure.rs
> [#21] Add tests for overriding DB TOML configs

- src/config/schema.rs
- src/err.rs
- src/lib.rs
- src/model/tool.rs
- src/sync.rs
- src/sync/configure.rs
- src/sync/install.rs
> [#11] Setup pretty error reporting with multiline errors and open issue suggestions

- .github/workflows/rust.yml
- example-tool-sync-config.toml
- tests/full-database.toml
- tests/only-ripgrep.toml
> [#15] Implement exe-checking test-suite for the entire hardcoded database

- .github/workflows/rust.yml
> [#30] Configure CI build cache

- .github/dependabot.yml
> [#9] Add dependabot

- .github/workflows/rust.yml
- example-tool-sync-config.toml
- src/model/asset_name.rs
- src/sync/archive.rs
- src/sync/db.rs
- src/sync/install.rs
- tests/full-database.toml
> [#5] Run CI in Ubuntu, macOS and Windows

- src/model/asset_name.rs
> [#8] Add tests for 'AssetName::get_name_by_os()'

- .github/CODEOWNERS
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- FUNDING.yml
> [#10] Add Community guidelines: Funding, Code of Conduct, Contributing

- Cargo.toml
> [#23] Improve Cargo.toml package metadata before publishing

- .github/workflows/rust.yml
- src/config/schema.rs
- src/config/toml.rs
- src/lib.rs
- src/main.rs
- src/model/asset_name.rs
- src/model/tool.rs
- src/sync/archive.rs
- src/sync/configure.rs
- src/sync/download.rs
> [#41] Configure clippy

- .github/workflows/release.yml
- Cargo.toml
> [#6] Setup binary releases

- .github/workflows/ci.yml
- src/sync/db.rs
- tests/full-database.toml
> [#46] Support tool-sync by tool-sync

- CHANGELOG.md
- src/sync/configure.rs
> [#55] Don't require 'exe_name' in the configuration

- .github/PULL_REQUEST_TEMPLATE.md
~Resolves #~
There is no issue for this since this change seems very low impact.
> [skip ci] added an extra checkbox for CHANGELOG changes

- src/config/toml.rs
Fixes #25 
Provide more detailed TOML decoding errors by adding `DecodeError` enum to represent different error types.
Author's questions:
> Does the toml crate provide better decoding than as_str() and friends? All such functions return Option<...> while it would be better to have Result<..., ...>
I couldn't find better decoding than as_str() but I did map `Option<>` to `Result<_, DecodeError>` so I guess dealing with Option is fine?
> Provide more detailed TOML decoding errors

- src/config/cli.rs
> [#141] Add docstring to the '--proxy' CLI flag

- src/infra/client.rs
> feat: remove double debug println calls
